export const ROUNDS = {
  POOL_TYPE: 'STYP$POOLS',
  CUMULATIVE_TYPE: 'STYP$CUMULATIVE',
  BRACKETS_TYPE: 'STYP$BRACKETS',
  RANKING: 'PTYP$RANKING',
  STAGE_TYPE: 'stage',
  PHASE_TYPE: 'phase',
  UNIT_TYPE: 'unit',
  FORGEROCK_REALM: 'dev',
};
